# Pandas tutorial

In [28]:
import pandas as pd
import numpy as np
import openpyxl

### np.nan یعنی اینجا هیچ چیز نیست مثلا سن و قد و اسم رو در یک مجموعه ای داریم ولی نمیدونیم اسم یه نفر چیه جاش nan میزنیم

In [6]:
a = pd.Series([1,6,85,"Mahdi",8,"Sara" , np.nan, -5 , -96])

In [7]:
pd.Series([[6,85,"Mahdi"] , 56])

0    [6, 85, Mahdi]
1                56
dtype: object

In [8]:
pd.Series([[[81,56,"Mahdi"] , [41, 12]]])

0    [[81, 56, Mahdi], [41, 12]]
dtype: object

### تاریخ

In [9]:
date = pd.date_range("20250228" , periods=10)
date

DatetimeIndex(['2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03',
               '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07',
               '2025-03-08', '2025-03-09'],
              dtype='datetime64[us]', freq='D')

### رندوم در نامپای

In [10]:
b = np.random.randn(10,5)

### دیتافریم پانداز

In [11]:
df = pd.DataFrame(b , index=date , columns=["Mahdi" , "Sara" , "Maman" , "Baba" , "Zahra"])
df

               Mahdi      Sara     Maman      Baba     Zahra
2025-02-28 -0.105615 -0.730306  1.476392  0.779319 -0.047767
2025-03-01  0.695517  0.189410  0.253030 -0.533278 -2.437051
2025-03-02 -1.289914 -1.382123  0.466994 -0.445168  1.125295
2025-03-03  1.383218  0.588839  0.845608  1.905410  1.149124
2025-03-04  1.032521 -0.355387 -0.112709 -0.641087  0.567701
2025-03-05 -0.656553  0.244589 -1.113125  1.201490  0.065124
2025-03-06  0.197826  0.644576  0.116933 -0.530471 -0.046940
2025-03-07 -0.844783 -0.087830  0.401771 -0.565347  0.338621
2025-03-08  0.514078  1.359463  0.041637  0.242489  1.292649
2025-03-09 -0.573806  0.625271 -0.759328 -0.475840  0.002286

In [12]:
df.dtypes

Mahdi    float64
Sara     float64
Maman    float64
Baba     float64
Zahra    float64
dtype: object

In [13]:
df.Sara

2025-02-28   -0.730306
2025-03-01    0.189410
2025-03-02   -1.382123
2025-03-03    0.588839
2025-03-04   -0.355387
2025-03-05    0.244589
2025-03-06    0.644576
2025-03-07   -0.087830
2025-03-08    1.359463
2025-03-09    0.625271
Freq: D, Name: Sara, dtype: float64

### اگر مقدار زیادی دیتا داشتیم و میخواستیم فقط قسمت بالاشو ببینیم که بفهمیم چی هست و با چی سروکار داریم از این فانکشن در پانداز استفاده میکنیم

In [14]:
df.head(0)

Empty DataFrame
Columns: [Mahdi, Sara, Maman, Baba, Zahra]
Index: []

In [15]:
df.head(1)

               Mahdi      Sara     Maman      Baba     Zahra
2025-02-28 -0.105615 -0.730306  1.476392  0.779319 -0.047767

In [16]:
df.head(2)

               Mahdi      Sara     Maman      Baba     Zahra
2025-02-28 -0.105615 -0.730306  1.476392  0.779319 -0.047767
2025-03-01  0.695517  0.189410  0.253030 -0.533278 -2.437051

In [17]:
df.head(3)

               Mahdi      Sara     Maman      Baba     Zahra
2025-02-28 -0.105615 -0.730306  1.476392  0.779319 -0.047767
2025-03-01  0.695517  0.189410  0.253030 -0.533278 -2.437051
2025-03-02 -1.289914 -1.382123  0.466994 -0.445168  1.125295

### اگه بخوام فقط آخر دیتافریمم رو ببینم :

In [18]:
df.tail(2)

               Mahdi      Sara     Maman      Baba     Zahra
2025-03-08  0.514078  1.359463  0.041637  0.242489  1.292649
2025-03-09 -0.573806  0.625271 -0.759328 -0.475840  0.002286

### فانکشن دیسکرایب در پانداز یه نگاه کلی از دیتا به ما میدهد. به محض اینکه دیتا خوانده شود با این فانکشن میتوان یه نگاهی نسبت به دیتا پیدا کرد

In [19]:
df.describe()

           Mahdi       Sara      Maman       Baba      Zahra
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.035249   0.109650   0.161720   0.093752   0.200904
std     0.875794   0.785593   0.739408   0.905134   1.066614
min    -1.289914  -1.382123  -1.113125  -0.641087  -2.437051
25%    -0.635866  -0.288498  -0.074122  -0.532576  -0.034634
50%     0.046105   0.217000   0.184982  -0.460504   0.201873
75%     0.650157   0.616163   0.450688   0.645112   0.985897
max     1.383218   1.359463   1.476392   1.905410   1.292649

### بیشترین مقدار مهدی رو به من بده

In [20]:
df["Mahdi"].max()

np.float64(1.3832184982073799)

### خط 2 تا 6 رو بهم بده (خود خط 2 حساب نمیشه دیگه درواقع خود 3 تا 6 رو میده )

In [21]:
df[2:6]

               Mahdi      Sara     Maman      Baba     Zahra
2025-03-02 -1.289914 -1.382123  0.466994 -0.445168  1.125295
2025-03-03  1.383218  0.588839  0.845608  1.905410  1.149124
2025-03-04  1.032521 -0.355387 -0.112709 -0.641087  0.567701
2025-03-05 -0.656553  0.244589 -1.113125  1.201490  0.065124

### ترنسپوز کردن یعنی جابجا کردن سطر و ستون با هم

In [22]:
df.T

,2025-02-28,2025-03-01,2025-03-02,2025-03-03,2025-03-04,2025-03-05,2025-03-06,2025-03-07,2025-03-08,2025-03-09
Mahdi,-0.105615,0.695517,-1.289914,1.383218,1.032521,-0.656553,0.197826,-0.844783,0.514078,-0.573806
Sara,-0.730306,0.189410,-1.382123,0.588839,-0.355387,0.244589,0.644576,-0.087830,1.359463,0.625271
Maman,1.476392,0.253030,0.466994,0.845608,-0.112709,-1.113125,0.116933,0.401771,0.041637,-0.759328
Baba,0.779319,-0.533278,-0.445168,1.905410,-0.641087,1.201490,-0.530471,-0.565347,0.242489,-0.475840
Zahra,-0.047767,-2.437051,1.125295,1.149124,0.567701,0.065124,-0.046940,0.338621,1.292649,0.002286

### read & wright operation

In [31]:
df.to_csv("pandas.csv")